#!/bin/sh

# Part of vpn-dealership
# https://github.com/coalfire/vpn-dealership

#FIXME
# THIS IS NOT FULLY FUNCTIONAL YET.
# To be run on your certificate authority machine,
# which is not your VPN server, right?

etc="/usr/local/etc/easy-rsa"
pki="$etc/pki"

server="$1"
dest="$2"
creds="$3"

# Prevent client certs pretending to be a server
./easyrsa build-server-full "$server" nopass

# copy CA, cert, key to the vpn server.
scp -i "$creds" $pki/ca.crt                $vpnserver:/etc/openvpn/server-ca.crt
scp -i "$creds" $pki/issued/"$server".crt  $vpnserver:/etc/openvpn/server.crt
scp -i "$creds" $pki/private/"$server".key $vpnserver:/etc/openvpn/server.key
