#!/bin/sh

# Part of vpn-dealership
# https://github.com/coalfire/vpn-dealership

# THIS IS NOT FULLY FUNCTIONAL YET.

mkdir -p /etc/openvpn/
# user nobody will need to be able to find files in this dir
chmod 711 /etc/openvpn/
mkdir /etc/openvpn/clients
chmod 755/etc/openvpn/clients
cd /etc/openvpn/

# Create a Diffie-Hellman parameter file to create ephemeral session keys.
openssl dhparam -out dh2048.pem 2048

# Create a TLS-auth key - this is a PSK which will help prevent DOS attacks.
openvpn --genkey --secret /etc/openvpn/tls-auth.key

# Allow forwarding of packets
sysctl net.ipv4.ip_forward=1
# And make it persistent across reboots.
printf 'sysctl net.ipv4.ip_forward = 1' >/etc/sysctl.d/50-ip_forward.conf

# service portion - systemd style
ln -s /lib/systemd/system/openvpn\@.service \
  /etc/systemd/system/multi-user.target.wants/openvpn\@server.service
systemctl -f enable openvpn@server.service
systemctl start openvpn@server.service
