#!/bin/sh

# THIS IS NOT FUNCTIONAL YET.

ver='3.0.1'
ersa="EasyRSA-$ver"
etc="/usr/local/etc/easy-rsa/pki"

cd "$HOME/src"
cd "$ersa"

server="$1"
client="$2"
dest="$2"
ssh_key="$3"

pki="$etc/$server"

set_pki() {
    printf 'set_var EASYRSA_PKI "%s"\n' "$pki" >vars
}

deliver_client_certs() {
    scp -i "$ssh_key" "$pki/ca.crt"              "$dest:/etc/openvpn/server-ca.crt"
    scp -i "$ssh_key" "$pki/issued/$client.crt"  "$dest:/etc/openvpn/client.crt"
    scp -i "$ssh_key" "$pki/private/$client.key" "$dest:/etc/openvpn/client.key"
    scp -i "$ssh_key" "$pki/tls-auth.key"        "$dest:/etc/openvpn/tls-auth.key"
    scp -i "$ssh_key" "$pki/client.conf"         "$dest:/etc/openvpn/client.conf"
}

set_pki
./easyrsa build-client-full "$client" nopass
deliver_client_certs

# scp the client cert, client key, client conf, server CA, tls-auth.key 
# to client.
# Create the CCD file for the client on the server, and chmod 644 it.
