#!/bin/sh

# THIS IS NOT FUNCTIONAL YET.

die() {
    status=$1
    shift
    warn "$@"
    exit $status
}

warn() {
    echo "$@" >&2
}

ver='3.0.1'
ersa="/usr/local/share/EasyRSA-$ver"
etc="/usr/local/etc/pki"

usage="USAGE: $0 SERVER CLIENT fetch ca|crt|key|tls|conf
       $0 SERVER CLIENT create"

cd "$ersa" || die 2 "Can not cd to $ersa"

server="$1"
client="$2"
action="$3"

pki="$etc/$server"

set_pki() {
    printf 'set_var EASYRSA_PKI "%s"\n' "$pki" >vars
}

create() {
    ./easyrsa build-client-full "$client" nopass
}

fetch() {
    test -f "$pki/private/$client.key" || die 8 "No such client $client"
    case "$to_fetch" in
      ca)
        path_to_file="$pki/ca.crt"
        ;;
      crt)
        path_to_file="$pki/issued/$client.crt"
        ;;
      key)
        path_to_file="$pki/private/$client.key"
        ;;
      tls)
        path_to_file="$pki/tls-auth.key"
        ;;
      conf)
        path_to_file="$pki/client.conf"
        ;;
      *)
        die 1 "$usage"
        ;;
    esac
    cat "$path_to_file" || die 4 "No such file $path_to_file"
}

test -d "$pki" || die 8 "No such CA $server"

set_pki

case "$action" in
  create)
    create
    ;;
  fetch)
    to_fetch="$4"
    fetch
    ;;
  *)
    die 1 "$usage"
    ;;
esac
