#!/bin/sh

# Part of vpn-dealership
# https://github.com/coalfire/vpn-dealership

# This sets up your Certificate Authority. 
# Do not run it on your VPN server.

mkdir -p src
cd src
ver='3.0.1'
ersa="EasyRSA-$ver"
wget "https://github.com/OpenVPN/easy-rsa/releases/download/$ver/$ersa.tgz"
tar xf "$ersa.tgz"
cd "$ersa"

# set pki directory for Easy RSA
etc="/usr/local/etc/easy-rsa"
mkdir -p "$etc"
pki="$etc/pki"
printf 'set_var EASYRSA_PKI "%s"\n' "$pki" >vars

# Make a PKI
./easyrsa init-pki
# Make the Certificate Authority
echo pwgen -y 64 1
./easyrsa build-ca

# Make an emply Certificate Revocation List
./easyrsa gen-crl
